// TRANSLATES

const translates = {
  en: {
    t1: 'Calculate Investment',
    t2: 'What we provide',
    t3: 'Deep Reef Investments main focus is our clients. We offer custom tailored membership experience and support.',
    t13: 'Our services',
    t14: '/first',
    t15: '/second',
    t16: '/third',
    t17: '/fourth',
    t18: '/fifth',
    t19: '/sixth',
    t21: 'Metal membership cards',
    t22: 'Investment plans',
    t23: 'Support 24/7',
    t24: 'Customer dashboard',
    t25: 'Сompliance',
    t26: 'Benefits & rewards',
    t28: 'When becoming a member of Deep Reef, our clients receive their own personalized metal membership cards.',
    t29: 'No client is the same! Based on our client’s investment goals and budget, we help to create an investment plan that suits the investor’s needs.',
    t30: 'No matter if you are located in england, moscow, or dubai, our dedicated managers are 24/7 available for you whenever you need their help.',
    t31: 'Our user-friendly personalized dashboard allows you to track your investments, contact your investment advisor, manage your money growth, and withdraw funds.',
    t32: 'To ensure transparency from both sides, Deep Reef runs a simple client check to ensure we remain compliant with AntiMoney Laundering Act 2018.',
    t33: 'While becoming a member of Deep Reef, you not only get a personalized membership card but also prestigious bonuses. The longer you stay, the more benefits you get!',
    t38: 'Personalised<br>investment plans',
    t39: "Based on how much capital and the term of length you're planning to invest, one of our members of staff will be in touch to an initial consultation to advise and come up with the most efficient solution to achieving your investment goal.",
    t40: 'Calculate Investment',
    t41: 'Want to get started',
    t42: "Just submit your information and we'll estimate your investment",
    t43: 'Calculate Investment',
    t44: 'Have any Questions?',
    t45: 'WhatsApp: +44 7946 704593',
    t46: 'Address: 111 Power Rd, Chiswick, London W4 4PY',
    t47: 'Email: request@deepreef.uk',
    t48: 'Quick links',
    t49: 'Home',
    t50: 'Our Services',
    t51: 'Contact us',
    t52: 'Calculator',
    t53: 'Instagram',
    t54: 'Sign up to receive our<br>updates and offers',
    t55: 'Sign up to updates',
    t56: 'Investor Dashboard',
    t57: 'Services',
    t58: 'Contact us',
    t59: 'Home',
    t60: 'Deep Reef Token',
    t61: 'Calculate Investment',
    t62: 'Video about Deep Reef'
  },
  ru: {
    t1: 'Рассчитать инвестиции',
    t2: 'Что мы предоставляем',
    t3: 'Основное внимание Deep Reef Investments направлено на наших клиентов. Мы предлагаем индивидуальный подход к членству и поддержку.',
    t13: 'Наши сервисы',
    t14: '/первое',
    t15: '/второе',
    t16: '/третье',
    t17: '/четвертое',
    t18: '/пятое',
    t19: '/шестое',
    t21: 'Металическая карта участника клуба',
    t22: 'Инвестиционные планы',
    t23: 'Поддержка 24/7',
    t24: 'Личный кабинет',
    t25: 'Соответствие',
    t26: 'Преимущества & награды',
    t28: 'Становясь членом Deep Reef, наши клиенты получают персональные металлические членские карты.',
    t29: 'Нет одинаковых клиентов! Основываясь на инвестиционных целях и бюджете нашего клиента, мы помогаем создать инвестиционный план, который соответствует потребностям инвестора.',
    t30: 'Независимо от того, находитесь ли вы в Англии, Москве или Дубае, наши преданные менеджеры доступны для вас 24 часа в сутки, 7 дней в неделю, когда вам нужна их помощь.',
    t31: 'Наша удобная персонализированная панель инструментов позволяет вам отслеживать свои инвестиции, связываться с вашим инвестиционным консультантом, управлять ростом вашего капитала и выводить средства.',
    t32: 'Чтобы обеспечить прозрачность с обеих сторон, Deep Reef проводит простую проверку клиентов, чтобы убедиться, что мы соблюдаем Закон о борьбе с отмыванием денег 2018 года.',
    t33: 'Став участником Deep Reef, вы получаете не только именную карту участника, но и престижные бонусы. Чем дольше вы остаетесь, тем больше преимуществ вы получаете!',
    t38: 'Индивидуальные инвестиционные планы',
    t39: 'В зависимости от того, сколько капитала и на какой срок вы планируете инвестировать, один из наших сотрудников свяжется с вами для первоначальной консультации, чтобы дать совет и предложить наиболее эффективное решение для достижения вашей инвестиционной цели.',
    t40: 'Рассчитать инвестиции',
    t41: 'Хотите начать',
    t42: 'Просто отправьте информацию, и мы оценим ваши инвестиции',
    t43: 'Рассчитать инвестиции',
    t44: 'Есть вопросы?',
    t45: 'WhatsApp: +44 7946 704593',
    t46: 'Адрес: 111 Power Rd, Chiswick, London W4 4PY',
    t47: 'Почта: request@deepreef.uk',
    t48: 'Меню',
    t49: 'Главная',
    t50: 'Наши сервисы',
    t51: 'Контакты',
    t52: 'Калькулятор',
    t53: 'Instagram',
    t54: 'Подпишитесь,<br>чтобы получать<br>наши обновления<br>и предложения',
    t55: 'Подписаться на обновления',
    t56: 'Панель инвестора',
    t57: 'Сервисы',
    t58: 'Контакты',
    t59: 'Главная',
    t60: 'Deep Reef Token',
    t61: 'Рассчитать инвестиции',
    t62: 'Видео о компании'
  }
}