// TRANSLATES

const translates = {
  en: {
    t1: 'Calculate Investment',
    t2: 'New era of Investment',
    t3: 'Deep Reef is a UK based investment company with more than 4 years of experience in the field of trading. Our aim is to make sure that your journey is smooth, easy, and stress -free, and we work with the following strategy.',
    t4: 'We are working through algorithmic tradingan automated trading system that helpsto choose the best investment options for our clients to receive the profits they are looking for.',
    t5: 'Our mission',
    t6: 'We pride ourselves to be one of the top investment consultancies in the investment advisory industry working on the 5 main pillars:',
    t7: 'Responsibility',
    t8: 'Safety',
    t9: 'Consistency',
    t10: 'As a team of professionals, we always work hard to achieve the best results at the highest standards. Our mission is to not only explain and advise on the investment but to deliver the results our clients are looking for.',
    t11: 'We know that safety and trust are priorities for our clients. We guarantee the highest standards of risk-management through the whole process. With our algorithmic trading system, you can be rest assured of 100% invested money back.',
    t12: 'Our automated trading system finds the best exchanges, stocks, and stock markets for the most profitable investment. Unlike other investment consultancies, the algorithmic system checks for the best investment options to receive the expected profit.',
    t13: 'Our clients’ satisfaction<br>is our priority',
    t14: '/first',
    t15: '/second',
    t16: '/third',
    t17: '/fourth',
    t18: '/fifth',
    t19: '/sixth',
    t20: '/seventh',
    t21: 'A happy client is a long time client!',
    t22: 'We strive for perfection in everything we do through',
    t23: 'Languages',
    t24: 'Currency',
    t25: 'Transparency',
    t26: 'Uniqueness',
    t27: '24/7 service',
    t28: 'We work hard to make sure that your investment process is easy and stress-free. Due to the level of perfection provided in our financial performance, customer service, and organizational productivity, an average investor stays with us for one and half years.',
    t29: 'We work hard to make sure that your investment process is easy and stress-free. Due to the level of perfection provided in our financial performance, customer service, and organizational productivity, an average investor stays with us for one and half years.',
    t30: 'Our investment advisors speak 7 languages: English, Russian, French, Arabic, Turkish, Kazakh, and Azerbaijani to ensure flawless communication.',
    t31: 'We work with such currencies as dollars, euro, pounds, rubles, and dirhams. If you have non of them, contact us and we will find a solution.',
    t32: 'Our user-friendly dashboard that is available 24/7 allows our clients to track and manage their money growth.',
    t33: 'We are the only investment consultancy where you can’t lose. Working through our algorithmic trading system, we guarantee 100% invested money back.',
    t34: 'No matter if you are in the UK, Russia, or the UAE, we are available 24/7 to assist you with any questions.',
    t35: 'Beneficial support packages<br>and exclusive membership',
    t36: ' Every client is different with his or her own goals and budget. Our tailor-made packages will fit your financial requirements and bring the expected results.',
    t37: 'After discussing all the benefits, capital growth, and the length of the investment, our advisors will come up with the most efficient individual solutions to achieve your investment goal.',
    t38: 'Personalised<br>investment plans',
    t39: "Based on how much capital and the term of length you're planning to invest, one of our members of staff will be in touch to an initial consultation to advise and come up with the most efficient solution to achieving your investment goal.",
    t40: 'Calculate Investment',
    t41: 'Want to get started',
    t42: "Just submit your information and we'll estimate your investment",
    t43: 'Calculate Investment',
    t44: 'Have any Questions?',
    t45: 'WhatsApp: +44 7946 704593',
    t46: 'Address: 111 Power Rd, Chiswick, London W4 4PY',
    t47: 'Email: request@deepreef.uk',
    t48: 'Quick links',
    t49: 'Home',
    t50: 'Our Services',
    t51: 'Contact us',
    t52: 'Calculator',
    t53: 'Instagram',
    t54: 'Sign up to receive our<br>updates and offers',
    t55: 'Sign up to updates',
    t56: 'Investor Dashboard',
    t57: 'Services',
    t58: 'Contact us',
    t59: 'Home',
    t60: 'Deep Reef Token',
    t61: 'Calculate Investment <span style="margin-left: 10px">→</span>',
    t62: 'Video about Deep Reef'
  },
  ru: {
    t1: 'Рассчитать инвестиции',
    t2: 'DeepReef token',
    t3: 'Откройте для себя инновационный способ инвестирования в фондовый рынок с помощью Deep Reef Token. Благодаря нашему проекту<br>с использованием искусственного интеллекта для торговли на бирже вы получите альтернативный источник пассивного дохода, для этого вам нужно будет держать токены нашего проекта DRT на своем холодном кошельке.<br><br>Подробнее: <a href="deepreeftoken.com" style="color: #1C71F8">deepreeftoken.com</a>',
    t13: 'Больше информации',
    t14: '/первое',
    t15: '/второе',
    t44: 'Есть вопросы?',
    t45: 'WhatsApp: +44 7946 704593',
    t46: 'Адрес: 111 Power Rd, Chiswick, London W4 4PY',
    t47: 'Почта: request@deepreef.uk',
    t48: 'Меню',
    t49: 'Главная',
    t50: 'Наши сервисы',
    t51: 'Контакты',
    t52: 'Калькулятор',
    t53: 'Instagram',
    t54: 'Подпишитесь,<br>чтобы получать<br>наши обновления<br>и предложения',
    t55: 'Подписаться на обновления',
    t56: 'Панель инвестора',
    t57: 'Сервисы',
    t58: 'Контакты',
    t59: 'Главная',
    t60: 'Deep Reef Token',
    t61: 'Рассчитать инвестиции <span style="margin-left: 10px">→</span>',
    t62: 'Видео о компании'
  }
}