// TRANSLATES

const translates = {
  en: {
    t1: 'Calculate Investment',
    t2: 'Сalculate your investment',
    t3: 'Calculate your estimated retirement savings with our investment calculator and use our service to help you reach your goal.',
    t35: ' Calculator',
    t36: 'First name',
    t37: 'Last name',
    t38: 'Email',
    t39: 'Mobile Number',
    t40: 'Amount',
    t41: 'Choose Currency',
    t42: 'How Long (Investment rounds)',
    t43: '*One investment round lasts 30 Days. Then we have 10 day grace period. After that next investment round starts',
    t431: 'Calculate Investment',
    t44: 'Have any Questions?',
    t45: 'WhatsApp: +44 7946 704593',
    t46: 'Address: 111 Power Rd, Chiswick, London W4 4PY',
    t47: 'Email: request@deepreef.uk',
    t48: 'Quick links',
    t49: 'Home',
    t50: 'Our Services',
    t51: 'Contact us',
    t52: 'Calculator',
    t53: 'Instagram',
    t54: 'Sign up to receive our<br>updates and offers',
    t55: 'Sign up to updates',
    t56: 'Investor Dashboard',
    t57: 'Services',
    t58: 'Contact us',
    t59: 'Home',
    t60: 'Deep Reef Token',
    t61: 'Calculate Investment',
    t62: 'Video about Deep Reef'
  },
  ru: {
    t1: 'Рассчитать инвестиции',
    t2: 'Рассчитайте свои инвестиции',
    t3: 'Рассчитайте свои предполагаемые пенсионные сбережения с помощью нашего инвестиционного калькулятора и воспользуйтесь нашим сервисом, чтобы помочь вам достичь своей цели.',
    t35: 'Калькулятор',
    t36: 'Ваше имя',
    t37: 'Ваша фамилия',
    t38: 'Ваша почта',
    t39: 'Ваш номер телефона',
    t40: 'Количество',
    t41: 'Выберите Валюту',
    t42: 'Как долго (инвестиционные раунды)',
    t43: '*Один инвестиционный раунд длится 30 дней. Затем у нас есть 10-дневный льготный период. <br>После этого начинается следующий инвестиционный раунд',
    t431: 'Рассчитать инвестиции',
    t44: 'Есть вопросы?',
    t45: 'WhatsApp: +44 7946 704593',
    t46: 'Адрес: 111 Power Rd, Chiswick, London W4 4PY',
    t47: 'Почта: request@deepreef.uk',
    t48: 'Меню',
    t49: 'Главная',
    t50: 'Наши сервисы',
    t51: 'Контакты',
    t52: 'Калькулятор',
    t53: 'Instagram',
    t54: 'Подпишитесь,<br>чтобы получать<br>наши обновления<br>и предложения',
    t55: 'Подписаться на обновления',
    t56: 'Панель инвестора',
    t57: 'Сервисы',
    t58: 'Контакты',
    t59: 'Главная',
    t60: 'Deep Reef Token',
    t61: 'Рассчитать инвестиции',
    t62: 'Видео о компании'
  }
}