// TRANSLATES

const translates = {
  en: {
    t1: 'Calculate Investment',
    t2: 'DeepReef token',
    t3: 'Discover an innovative way to invest in the stock market with Deep Reef Token. Thanks to our project using artificial intelligence for trading on the exchange, you will receive an alternative source of passive income, for this you will need to hold the tokens of our DRT project on your cold wallet.<br><br>Read more: <a href="deepreeftoken.com" style="color: #1C71F8">deepreeftoken.com</a>',
    t13: 'More information',
    t14: '/first',
    t15: '/second',
    t21: 'Telegram bot',
    t22: 'Twitter',
    t44: 'Have any Questions?',
    t45: 'WhatsApp: +44 7946 704593',
    t46: 'Address: 111 Power Rd, Chiswick, London W4 4PY',
    t47: 'Email: request@deepreef.uk',
    t48: 'Quick links',
    t49: 'Home',
    t50: 'Our Services',
    t51: 'Contact us',
    t52: 'Calculator',
    t53: 'Instagram',
    t54: 'Sign up to receive our<br>updates and offers',
    t55: 'Sign up to updates',
    t56: 'Investor Dashboard',
    t57: 'Services',
    t58: 'Contact us',
    t59: 'Home',
    t60: 'Deep Reef Token',
    t61: 'Calculate Investment',
    t62: 'Video about Deep Reef',
    t63: 'Subscribe to receive our updates and offers',
    t64: 'Subscribe'
  },
  ru: {
    t1: 'Рассчитать инвестиции',
    t2: 'DeepReef token',
    t3: 'Откройте для себя инновационный способ инвестирования в фондовый рынок с помощью Deep Reef Token. Благодаря нашему проекту<br>с использованием искусственного интеллекта для торговли на бирже вы получите альтернативный источник пассивного дохода, для этого вам нужно будет держать токены нашего проекта DRT на своем холодном кошельке.<br><br>Подробнее: <a href="deepreeftoken.com" style="color: #1C71F8">deepreeftoken.com</a>',
    t13: 'Больше информации',
    t14: '/первое',
    t15: '/второе',
    t21: 'Telegram bot',
    t22: 'Twitter',
    t44: 'Есть вопросы?',
    t45: 'WhatsApp: +44 7946 704593',
    t46: 'Адрес: 111 Power Rd, Chiswick, London W4 4PY',
    t47: 'Почта: request@deepreef.uk',
    t48: 'Меню',
    t49: 'Главная',
    t50: 'Наши сервисы',
    t51: 'Контакты',
    t52: 'Калькулятор',
    t53: 'Instagram',
    t54: 'Подпишитесь,<br>чтобы получать<br>наши обновления<br>и предложения',
    t55: 'Подписаться на обновления',
    t56: 'Панель инвестора',
    t57: 'Сервисы',
    t58: 'Контакты',
    t59: 'Главная',
    t60: 'Deep Reef Token',
    t61: 'Рассчитать инвестиции',
    t62: 'Видео о компании',
    t63: 'Подпишитесь, чтобы получать наши обновления и предложения',
    t64: 'Подписаться'
  }
}