// TRANSLATES

const translates = {
  en: {
    t1: 'Calculate Investment',
    t2: 'Have any question',
    t3: 'For Deep Reef Investments our clients’ happiness and satisfaction are our priority. We offer a VIP experience and support to every member.',
    t13: 'Сontact us',
    t14: '/first',
    t15: '/second',
    t16: '/third',
    t21: 'Whatsapp',
    t22: 'Email',
    t23: 'Address',
    t28: 'Call us or send a WhatsApp message and we will be happy to answer all your questions. +44 7946 704593',
    t29: ' Send us an email or fill in the form, and our investment manager will contact you shortly. ',
    t30: 'We are located in 111 Power Rd,<br>Chiswick, London W4 5PY',
    t38: 'Get in touch',
    t39: "Please get in touch and we’ll be happy to assist you.",
    t401: 'Your name',
    t402: 'Email address',
    t403: 'Subject',
    t404: 'Message',
    t405: 'Send message',
    t41: 'Want to get started',
    t42: "Just submit your information and we'll estimate your investment",
    t43: 'Calculate Investment',
    t44: 'Have any Questions?',
    t45: 'WhatsApp: +44 7946 704593',
    t46: 'Address: 111 Power Rd, Chiswick, London W4 4PY',
    t47: 'Email: request@deepreef.uk',
    t48: 'Quick links',
    t49: 'Home',
    t50: 'Our Services',
    t51: 'Contact us',
    t52: 'Calculator',
    t53: 'Instagram',
    t54: 'Sign up to receive our<br>updates and offers',
    t55: 'Sign up to updates',
    t56: 'Investor Dashboard',
    t57: 'Services',
    t58: 'Contact us',
    t59: 'Home',
    t60: 'Deep Reef Token',
    t61: 'Calculate Investment →',
    t62: 'Video about Deep Reef'
  },
  ru: {
    t1: 'Рассчитать инвестиции',
    t2: 'Есть вопросы',
    t3: 'Для Deep Reef Investments счастье и удовлетворение наших клиентов являются нашим приоритетом. Мы предлагаем VIP-опыт и поддержку каждому участнику.',
    t13: 'Контакты',
    t14: '/первое',
    t15: '/второе',
    t16: '/третье',
    t21: 'Whatsapp',
    t22: 'Почта',
    t23: 'Адрес',
    t28: 'Позвоните нам или отправьте сообщение<br>в WhatsApp, и мы будем рады ответить на все ваши вопросы. +44 7946 704593',
    t29: 'Отправьте нам электронное письмо или заполните форму, и наш инвестиционный менеджер <br>с вами в ближайшее время. ',
    t30: 'Мы находимся на 111 Power Rd,<br>Chiswick, London W4 5PY',
    t38: 'Связаться',
    t39: 'Пожалуйста, свяжитесь с нами, и мы будем рады помочь вам.',
    t401: 'Ваше имя',
    t402: 'Ваша почта',
    t403: 'Проблема',
    t404: 'Сообщение',
    t405: 'Отправить форму',
    t41: 'Хотите начать',
    t42: 'Просто отправьте информацию, и мы оценим ваши инвестиции',
    t43: 'Рассчитать инвестиции',
    t44: 'Есть вопросы?',
    t45: 'WhatsApp: +44 7946 704593',
    t46: 'Адрес: 111 Power Rd, Chiswick, London W4 4PY',
    t47: 'Почта: request@deepreef.uk',
    t48: 'Меню',
    t49: 'Главная',
    t50: 'Наши сервисы',
    t51: 'Контакты',
    t52: 'Калькулятор',
    t53: 'Instagram',
    t54: 'Подпишитесь,<br>чтобы получать<br>наши обновления<br>и предложения',
    t55: 'Подписаться на обновления',
    t56: 'Панель инвестора',
    t57: 'Сервисы',
    t58: 'Контакты',
    t59: 'Главная',
    t60: 'Deep Reef Token',
    t61: 'Рассчитать инвестиции →',
    t62: 'Видео о компании'
  }
}